from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_equipment, name='list_equipment'),
    path('add/', views.add_equipment, name='add_equipment'),
    path('edit/<int:pk>/', views.edit_equipment, name='edit_equipment'),
    path('delete/<int:pk>/', views.delete_equipment, name='delete_equipment'),
    path('actions/', views.list_actions, name='list_actions'),
    path('equipment/<int:equipment_id>/action/', views.add_equipment_action, name='add_equipment_action'),
    path('equipment/<int:equipment_id>/actions/', views.equipment_actions, name='equipment_actions'),
    path('equipment/export/csv/', views.export_equipment_csv, name='export_equipment_csv'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('files/delete/<int:pk>/', views.delete_file, name='delete_file'),
    path('tickets/new/', views.create_request_ticket, name='create_ticket'),
    path('tickets/', views.list_tickets, name='list_tickets'),
    path('articles/', views.list_articles, name='list_articles'),
    path('articles/<int:article_id>/', views.view_article, name='view_article'),
    path('reports/tickets/', views.report_tickets, name='report_tickets'),
    path('feedback/list/', views.list_feedback, name='list_feedback'),
    path('feedback/<int:pk>/', views.feedback_detail, name='feedback_detail'),
    path('feedback/delete/<int:pk>/', views.delete_feedback, name='delete_feedback'),
    path('equipment/<int:equipment_id>/files/', views.equipment_files, name='equipment_files'),
    path('equipment/<int:equipment_id>/files/upload/', views.upload_file, name='upload_file'),
    path('tickets/<int:ticket_id>/status/<str:new_status>/', views.update_ticket_status, name='update_ticket_status'),
    path("admin-panel/users/", views.admin_user_list, name="admin_user_list"),
    path("admin-panel/users/<int:user_id>/edit/", views.edit_user, name="edit_user"),
    path("admin-panel/users/<int:user_id>/edit/", views.edit_user, name="edit_user"),
    path("admin-panel/users/<int:user_id>/delete/", views.delete_user, name="delete_user"),
    path("admin-panel/users/<int:user_id>/password/", views.change_password, name="change_password"),
    path("admin-panel/users/create/", views.create_user, name="create_user"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("admin-panel/", views.admin_dashboard, name="admin_dashboard"),
    path("tech-panel/", views.tech_dashboard, name="tech_dashboard"),
    path("user-panel/", views.user_dashboard, name="user_dashboard"),
    path("tickets/<int:ticket_id>/status/<str:new_status>/", views.update_ticket_status, name="update_ticket_status"),
    path("reports/dashboard/", views.report_dashboard, name="report_dashboard"),
    path("reports/export/csv/", views.export_tickets_csv, name="export_tickets_csv"),
]
