# Generated by Django 5.2.1 on 2025-06-03 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('inventory_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in_use', 'В эксплуатации'), ('under_repair', 'В ремонте'), ('written_off', 'Списано')], max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
