# Generated by Django 5.2.1 on 2025-08-14 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orgvitte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('repair', 'Ремонт'), ('movement', 'Перемещение'), ('decommission', 'Списание')], max_length=20, verbose_name='Тип действия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('from_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Откуда')),
                ('to_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Куда')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orgvitte.equipment', verbose_name='Оборудование')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
            ],
        ),
    ]
