# Generated by Django 5.2.1 on 2025-08-23 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orgvitte', '0002_equipmentaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='barcode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Штрих-код'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(max_length=100, verbose_name='Тип оборудования'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('in_use', 'В эксплуатации'), ('under_repair', 'В ремонте'), ('written_off', 'Списано')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipmentaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
