# Generated by Django 5.2.1 on 2025-10-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orgvitte', '0002_requestticket_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestticket',
            name='contact_info',
            field=models.CharField(default='- не указано -', max_length=255, verbose_name='Контактные данные заявителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestticket',
            name='department',
            field=models.CharField(default='- не указано -', max_length=255, verbose_name='Отдел / подразделение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestticket',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tickets_photos/', verbose_name='Фото неисправности'),
        ),
        migrations.AddField(
            model_name='requestticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='requestticket',
            name='repair_date',
            field=models.DateField(blank=True, null=True, verbose_name='Желаемая дата ремонта'),
        ),
    ]
