# Generated by Django 5.2.1 on 2025-09-04 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orgvitte', '0003_alter_equipment_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('cartridge', 'Замена картриджа'), ('repair', 'Ремонт'), ('phone', 'Смена внутреннего номера телефона')], max_length=50, verbose_name='Тип заявки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orgvitte.equipment', verbose_name='Оборудование')),
            ],
        ),
    ]
