# Generated by Django 5.2.1 on 2025-09-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orgvitte', '0005_alter_equipment_added_at_alter_equipment_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='requestticket',
            name='title',
            field=models.CharField(default=' ', max_length=200, verbose_name='Тема заявки'),
            preserve_default=False,
        ),
    ]
